Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  # Define cluster nodes
  nodes = [
    { name: "k8s-master", ip: "192.168.56.10", cpus: 2, memory: 2048 },
    { name: "k8s-worker1", ip: "192.168.56.11", cpus: 1, memory: 1024 },
    { name: "k8s-worker2", ip: "192.168.56.12", cpus: 1, memory: 1024 }
  ]

  nodes.each do |node|
    config.vm.define node[:name] do |node_config|
      node_config.vm.hostname = node[:name]
      node_config.vm.network "private_network", ip: node[:ip]

      node_config.vm.provider "virtualbox" do |vb|
        vb.name = node[:name]
        vb.cpus = node[:cpus]
        vb.memory = node[:memory]
        # The following lines are a fix for AMD processors when attempting to pass CPU virtualization capabilities down into the VM
        vb.customize ["modifyvm", :id, "--nested-hw-virt", "off"]
        vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
      end
    end
  end

  # Run Ansible provisioner from the host machine on the master node
  config.vm.define "k8s-master" do |master|
    master.vm.provision "ansible" do |ansible|
      ansible.playbook = "../ansible/playbook.yml"
      ansible.inventory_path = "../ansible/inventory.ini"
      ansible.limit = "all"
    end
  end
end