Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  # Define cluster nodes
  nodes = [
    { name: "k8s-worker1", ip: "192.168.56.11", cpus: 1, memory: 1024 },
    { name: "k8s-worker2", ip: "192.168.56.12", cpus: 1, memory: 1024 },
    { name: "k8s-master",  ip: "192.168.56.10", cpus: 2, memory: 2048 }
  ]

  nodes.each do |node|
    config.vm.define node[:name] do |subconfig|
      subconfig.vm.hostname = node[:name]
      subconfig.vm.network "private_network", ip: node[:ip]

      subconfig.vm.provider "virtualbox" do |vb|
        vb.name = node[:name]
        vb.cpus = node[:cpus]
        vb.memory = node[:memory]
      end
    end
  end

  # Run Ansible provisioner from host on k8s-master (which runs last)
  config.vm.define "k8s-master" do |master|
    master.vm.provision "ansible" do |ansible|
      ansible.playbook = "../ansible/playbook.yml"
      ansible.inventory_path = "../ansible/inventory.ini"
      ansible.limit = "all"
    end
  end
end